import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { DomainStore, matchesKey, messagesKey, now, profileIndexKey, profileKey, searchFiltersKey, userId, profileSummary, validTelegramUsername, withTelegramDefaults, type Profile } from "../domain.js";
import { adminChatId, inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";

registerMainMenuItem({ label: "Мой профиль", data: "profile:manage", order: 30 });
const composer = new Composer<Ctx>();
const back = inlineKeyboard([[inlineButton("⬅️ В меню", "menu:main")]]);
const menu = back;
const force = (placeholder: string) => ({ force_reply: true as const, input_field_placeholder: placeholder });
const fields = inlineKeyboard([[inlineButton("Имя", "profile:edit:name"), inlineButton("Возраст", "profile:edit:age")], [inlineButton("Город", "profile:edit:city"), inlineButton("Семейный статус", "profile:edit:maritalStatus")], [inlineButton("Образование", "profile:edit:education"), inlineButton("Профессия", "profile:edit:profession")], [inlineButton("Рост", "profile:edit:height"), inlineButton("О себе", "profile:edit:bio")], [inlineButton("Цель знакомства", "profile:edit:purpose")], [inlineButton("Telegram", "profile:edit:telegram")], [inlineButton("⬅️ Назад", "profile:manage")]]);
function manageKeyboard(p: Profile) { const profile = withTelegramDefaults(p); return inlineKeyboard([[inlineButton("Изменить поле", "profile:edit:fields")], [inlineButton("Управление фото", "profile:photos:manage")], [inlineButton(`Показывать мой Telegram при взаимной симпатии: ${profile.showTelegramOnMatch ? "Да" : "Нет"}`, "profile:telegram:toggle")], [inlineButton(profile.visibility ? "Скрыть профиль" : "Показать профиль", "profile:visibility:toggle")], [inlineButton("Предпросмотр", "profile:preview"), inlineButton("Удалить профиль", "profile:delete")], [inlineButton("⬅️ В меню", "menu:main")]]); }
async function show(ctx: Ctx): Promise<void> { const stored = await new DomainStore(ctx).get<Profile>(profileKey(userId(ctx))); if (!stored) { await ctx.reply("У вас пока нет профиля — создайте его за несколько минут.", { reply_markup: inlineKeyboard([[inlineButton("Создать профиль", "profile:create:start")], [inlineButton("⬅️ В меню", "menu:main")]]) }); return; } const p = withTelegramDefaults(stored); await ctx.reply(profileSummary(p), { reply_markup: manageKeyboard(p) }); }
composer.callbackQuery("profile:manage", async (ctx) => { await ctx.answerCallbackQuery(); await show(ctx); });
composer.callbackQuery("profile:edit:fields", async (ctx) => { await ctx.answerCallbackQuery(); await ctx.editMessageText("Что хотите изменить?", { reply_markup: fields }); });
composer.callbackQuery("profile:edit:maritalStatus", async (ctx) => { await ctx.answerCallbackQuery(); await ctx.reply("Выберите семейный статус.", { reply_markup: inlineKeyboard([[inlineButton("Не был(а) в браке", "profile:marital:set:single")], [inlineButton("В отношениях", "profile:marital:set:relationship")], [inlineButton("Разведён(а)", "profile:marital:set:divorced")], [inlineButton("Вдовец или вдова", "profile:marital:set:widowed")]]) }); });
composer.callbackQuery(/^profile:marital:set:(single|relationship|divorced|widowed)$/, async (ctx) => { await ctx.answerCallbackQuery(); const p = await new DomainStore(ctx).get<Profile>(profileKey(userId(ctx))); if (!p) { await ctx.reply("Профиль не найден."); return; } p.maritalStatus = ({ single: "Не был(а) в браке", relationship: "В отношениях", divorced: "Разведён(а)", widowed: "Вдовец или вдова" } as Record<string, string>)[ctx.match[1]]; p.updatedAt = now(); await new DomainStore(ctx).set(profileKey(p.userId), p); await ctx.reply("Семейный статус обновлён.", { reply_markup: inlineKeyboard([[inlineButton("Мой профиль", "profile:manage")]]) }); });
composer.callbackQuery(/^profile:edit:(name|age|city|education|profession|height|bio|purpose|telegram)$/, async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.editField = ctx.match[1]; ctx.session.step = "edit_field"; const labels: Record<string, string> = { name: "имя", age: "возраст от 18 до 99", city: "город", education: "образование", profession: "профессию", height: "рост от 120 до 230 см", bio: "рассказ о себе", purpose: "цель знакомства", telegram: "Telegram без символа @" }; await ctx.reply(`Введите ${labels[ctx.match[1]]}.`, { reply_markup: force("Введите новое значение") }); });
composer.on("message:text", async (ctx, next) => { if (ctx.session.step !== "edit_field" || !ctx.session.editField) { await next(); return; } const value = ctx.message.text.trim(); const field = ctx.session.editField; const stored = await new DomainStore(ctx).get<Profile>(profileKey(userId(ctx))); if (!stored) { ctx.session.step = "idle"; await ctx.reply("Профиль не найден. Создайте его заново."); return; } const p = withTelegramDefaults(stored); if (!value || value.length > 500) { await ctx.reply("Значение должно быть от 1 до 500 символов.", { reply_markup: force("Введите новое значение") }); return; } if (field === "telegram") { if (!validTelegramUsername(value)) { await ctx.reply("Укажите Telegram без @: от 5 до 32 латинских букв, цифр или _.", { reply_markup: force("Например, anna_2026") }); return; } p.telegramUsername = value; p.telegram_username = value; } else if (field === "age") { const n = Number(value); if (!Number.isInteger(n) || n < 18 || n > 99) { await ctx.reply("Укажите возраст от 18 до 99 лет.", { reply_markup: force("Введите возраст") }); return; } p.age = n; } else if (field === "height") { const n = Number(value); if (!Number.isInteger(n) || n < 120 || n > 230) { await ctx.reply("Укажите рост от 120 до 230 сантиметров.", { reply_markup: force("Например, 170") }); return; } p.height = n; } else (p as unknown as Record<string, unknown>)[field] = value; p.updatedAt = now(); await new DomainStore(ctx).set(profileKey(p.userId), p); ctx.session.step = "idle"; ctx.session.editField = undefined; await ctx.reply("Изменения сохранены.", { reply_markup: inlineKeyboard([[inlineButton("Открыть профиль", "profile:manage")]]) }); });
composer.callbackQuery("profile:telegram:toggle", async (ctx) => { await ctx.answerCallbackQuery(); const store = new DomainStore(ctx); const stored = await store.get<Profile>(profileKey(userId(ctx))); if (!stored) { await ctx.reply("Сначала создайте профиль."); return; } const p = withTelegramDefaults(stored); p.showTelegramOnMatch = !p.showTelegramOnMatch; p.show_telegram_on_match = p.showTelegramOnMatch; p.updatedAt = now(); await store.set(profileKey(p.userId), p); await ctx.editMessageText("Настройка Telegram обновлена.", { reply_markup: manageKeyboard(p) }); });
composer.callbackQuery("profile:visibility:toggle", async (ctx) => { await ctx.answerCallbackQuery(); const store = new DomainStore(ctx); const p = await store.get<Profile>(profileKey(userId(ctx))); if (!p) { await ctx.reply("Сначала создайте профиль."); return; } p.visibility = !p.visibility; p.updatedAt = now(); await store.set(profileKey(p.userId), p); await ctx.editMessageText(p.visibility ? "Профиль снова виден другим людям." : "Профиль скрыт и не показывается в знакомствах.", { reply_markup: manageKeyboard(p) }); });
composer.callbackQuery("profile:preview", async (ctx) => { await ctx.answerCallbackQuery(); const p = await new DomainStore(ctx).get<Profile>(profileKey(userId(ctx))); if (!p) { await ctx.reply("Сначала создайте профиль."); return; } if (p.photos[0]) await ctx.replyWithPhoto(p.photos[0], { caption: profileSummary(p), reply_markup: back }); else await ctx.reply(profileSummary(p), { reply_markup: back }); });
composer.callbackQuery("profile:photos:manage", async (ctx) => { await ctx.answerCallbackQuery(); const p = await new DomainStore(ctx).get<Profile>(profileKey(userId(ctx))); if (!p) { await ctx.reply("Сначала создайте профиль."); return; } const rows = p.photos.map((_, i) => [inlineButton(i === 0 ? `Главное фото ${i + 1}` : `Сделать главным ${i + 1}`, `profile:photo:primary:${i}`), inlineButton(`Удалить ${i + 1}`, `profile:photo:delete:${i}`)]); await ctx.reply(`У вас ${p.photos.length} фото. Первое — главное.`, { reply_markup: inlineKeyboard([...rows, [inlineButton("Добавить фото", "profile:photo:add")], [inlineButton("⬅️ К профилю", "profile:manage")]]) }); });
composer.callbackQuery("profile:photo:add", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = "photos"; await ctx.reply("Пришлите фото. Можно добавить до 6 фотографий."); });
composer.on("message:photo", async (ctx, next) => { if (ctx.session.step !== "photos") { await next(); return; } const p = await new DomainStore(ctx).get<Profile>(profileKey(userId(ctx))); const photo = ctx.message.photo.at(-1); if (!p || !photo) { await ctx.reply("Не удалось добавить фото. Попробуйте ещё раз."); return; } if (p.photos.length >= 6) { await ctx.reply("Можно добавить не больше 6 фотографий."); return; } p.photos.push(photo.file_id); p.updatedAt = now(); await new DomainStore(ctx).set(profileKey(p.userId), p); ctx.session.step = "idle"; await ctx.reply("Фото добавлено и профиль обновлён.", { reply_markup: inlineKeyboard([[inlineButton("Управление фото", "profile:photos:manage")], [inlineButton("Мой профиль", "profile:manage")]]) }); });
composer.callbackQuery(/^profile:photo:delete:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const i = Number(ctx.match[1]); const store = new DomainStore(ctx); const p = await store.get<Profile>(profileKey(userId(ctx))); if (!p || i < 0 || i >= p.photos.length) { await ctx.reply("Это фото уже недоступно."); return; } if (p.photos.length === 1) { await ctx.reply("Оставьте хотя бы одну фотографию."); return; } p.photos.splice(i, 1); p.updatedAt = now(); await store.set(profileKey(p.userId), p); await ctx.editMessageText("Фото удалено. Профиль обновлён.", { reply_markup: inlineKeyboard([[inlineButton("Управление фото", "profile:photos:manage")], [inlineButton("Мой профиль", "profile:manage")]]) }); });
composer.callbackQuery(/^profile:photo:primary:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const i = Number(ctx.match[1]); const store = new DomainStore(ctx); const p = await store.get<Profile>(profileKey(userId(ctx))); if (!p || i < 0 || i >= p.photos.length) { await ctx.reply("Это фото уже недоступно."); return; } const [photo] = p.photos.splice(i, 1); p.photos.unshift(photo); p.updatedAt = now(); await store.set(profileKey(p.userId), p); await ctx.editMessageText("Главное фото обновлено.", { reply_markup: inlineKeyboard([[inlineButton("Управление фото", "profile:photos:manage")], [inlineButton("Мой профиль", "profile:manage")]]) }); });
composer.callbackQuery("profile:delete", async (ctx) => { await ctx.answerCallbackQuery(); await ctx.reply("Удалить профиль и все связанные данные? Это нельзя отменить.", { reply_markup: inlineKeyboard([[inlineButton("Удалить профиль", "profile:delete:confirm"), inlineButton("Оставить", "profile:manage")]]) }); });
composer.callbackQuery("profile:delete:confirm", async (ctx) => {
  await ctx.answerCallbackQuery();
  const id = userId(ctx);
  const store = new DomainStore(ctx);
  const p = await store.get<Profile>(profileKey(id));
  const profileIds = await store.get<number[]>(profileIndexKey()) ?? [];
  const matchIds = await store.get<string[]>(matchesKey(id)) ?? [];
  for (const candidate of profileIds) {
    if (candidate === id) continue;
    const likes = await store.get<Array<{ from_user_id?: number; to_user_id?: number; from?: number; to?: number }>>(`likes:${candidate}`) ?? [];
    await store.set(`likes:${candidate}`, likes.filter((like) => (like.to_user_id ?? like.to) !== id && (like.from_user_id ?? like.from) !== id));
  }
  for (const matchId of matchIds) {
    const match = await store.get<{ user_a_id?: number; user_b_id?: number }>(`match:${matchId}`);
    const other = match && (match.user_a_id === id ? match.user_b_id : match.user_a_id);
    if (other) {
      const otherMatches = await store.get<string[]>(matchesKey(other)) ?? [];
      await store.set(matchesKey(other), otherMatches.filter((value) => value !== matchId));
      try { await ctx.api.sendMessage(other, "Пользователь удалил профиль. Этот разговор больше недоступен."); } catch { /* blocked users are safe to ignore */ }
    }
    await store.delete(messagesKey(matchId));
    await store.delete(`match:${matchId}`);
  }
  await store.delete(profileKey(id));
  await store.delete(searchFiltersKey(id));
  await store.delete(`likes:${id}`);
  await store.delete(matchesKey(id));
  await store.set(profileIndexKey(), profileIds.filter((candidate) => candidate !== id));
  const admin = adminChatId(ctx);
  if (admin) { try { await ctx.api.sendMessage(admin, `Пользователь удалил профиль${p ? `: ${p.name}` : "."}`); } catch { /* best effort */ } }
  ctx.session.step = "idle";
  await ctx.reply("Профиль удалён. Спасибо, что доверяли нам.", { reply_markup: menu });
});
export default composer;
